### ISSUE TITLE
Move `RollbarSinkExtensions` to the `Serilog` namespace

### ISSUE THREAD

**Issue by tsimbalar** [olsh/serilog-sinks-rollbar#1]
Hi,

I would suggest you move the class `RollbarSinkExtensions` to the `Serilog` namespace, so that it automatically appears for users when configuring their Serilog pipeline. This will also provide a user experience that is consistent with the rest of the ecosystem. 

Cheers !

**Comment by olsh** [comment]
Thank you! 👍
