### ISSUE TITLE
Add support for host and code version when logging

### ISSUE THREAD

**Issue by lunyx** [olsh/serilog-sinks-rollbar#2]
When an email from rollbar is received, the code version and host are both unspecified. 

Project: | ProjectName
Environment: | production
Code Version: | unspecified
Host: | unspecified
Timestamp: | 2018-05-15   06:43 am

We can add support for this by setting the `Server` object on `RollbarConfig`, which contains the properties for `CodeVersion` and `Host`.

Will be creating a PR for this soon, and hoping that the nuget can be updated as well.

**Comment by olsh** [comment]
> hoping that the nuget can be updated as well.

Done, will be available within two hours, thank you!

**Comment by lunyx** [comment]
Thanks, that was a lot faster than I expected.  I can confirm that the values are going through to Rollbar in the updated package correctly as well.
